"""requirements.txt must stay a uv export, not a second dependency list."""

from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_REQUIREMENTS = _ROOT / "requirements.txt"
_PYPROJECT = _ROOT / "pyproject.toml"


def test_requirements_txt_is_marked_as_uv_export():
    """Docker install file must be generated by uv, not maintained by hand."""
    header = _REQUIREMENTS.read_text(encoding="utf-8").splitlines()[:3]
    assert header[0].startswith("# This file was autogenerated by uv")
    assert "uv export --format requirements-txt --no-hashes" in header[1]


def test_httpx2_is_not_an_extra():
    """httpx2 was a stray extra; TestClient uses httpx."""
    text = _PYPROJECT.read_text(encoding="utf-8")
    assert '"httpx2"' not in text
    assert '"httpx"' in text
